name: CI/CD Flask-Azure
on:
  push:
    branches:
    - "**"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      # - name: Test Unitaire
      #   run: python3 test.py
